### ISSUE TITLE
Make it work on tab groups

### ISSUE THREAD

**Issue by Edu4rdSHL** [xordiv/open-last-tab-chrome#2]
Hi, thank you for the great work. However, it doesn't work on tab group's tabs, it simply doesn't switch or do anything there.

Thanks!

**Comment by BlueBull010** [comment]
I second this request. Since the functionality for tab groups has been added, I've been using it extensively and have almost all of my tabs open inside a tab group. It would be great if we could also cycle tabs inside these groups

**Comment by Edu4rdSHL** [comment]
It was due to a [Chromium bug](https://issues.chromium.org/issues/323982812) which is fixed now.
